# ================= API SETTINGS =================
api:
  #model: "gpt-4-turbo"
  model: "gpt-4o"
  temperature: 0.2
  max_retries: 3
  timeout: 30

# ================= PATHS =================
paths:
  output_base_dir: 'C:/Users/FPT SHOP/CODING PROBLEM/LLM via FSCIL/LLM-description'